#!/usr/bin/env perl
use strict;
use warnings;
use IO::Dir;
my @argv = ();
for my $arg (@ARGV) {
  if ($arg =~ /^\d+$/) {
    my $d = new IO::Dir("/proc/$arg/task");
    if (defined($d)) {
      while (my $e = $d->read()) {
	if ($e =~ /^\d+$/) {
	  push(@argv, $e);
	}
      }
    }
  } else {
    push(@argv, $arg);
  }
}
exec("bulkdbg", @argv);
